#pragma once

#ifndef __CREATE_PROCESS_INJECT__
#define __CREATE_PROCESS_INJECT__


#define SHELLCODE_SIZE (43 + MAX_PATH)

#define SHELLCODE_DLL_PATH 43
#define SHELLCODE_DLL_PATH_ADDR 7
#define SHELLCODE_DLL_PATH_OFFSET 32

#define SHELLCODE_LOAD_LIBRARY_ENTRY 35
#define SHELLCODE_LOAD_LIBRARY_ENTRY_ADDR 13
#define SHELLCODE_LOAD_LIBRARY_ENTRY_OFFSET 18

#define SHELLCODE_RIP 27
#define SHELLCODE_RIP_ADDR 23
#define SHELLCODE_RIP_OFFSET 0

BOOL CreateProcessAndDoInject(LPCWSTR szProcessName);
LPBYTE  GetExeEntryPoint(PCSTR filename);


#endif // !__CREATE_PROCESS_INJECT__
